name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Run Flake8
        run: poetry run flake8 src/

      - name: Run Pylint
        run: |
          SCORE=$(poetry run pylint src/ | tee pylint.log | tail -n 2 | grep 'Your code has been rated at' | awk '{print $7}' | cut -d'/' -f1)
          echo "Pylint score: $SCORE"
          if (( $(echo "$SCORE < 9.0" | bc -l) )); then
            echo "Pylint score is below 9.0. Failing the build."
            exit 1
          fi