# .github/workflows/promote-dev.yml

name: Promote Dev to Main

# Trigger this workflow on every push to the 'dev' branch
on:
  push:
    branches:
      - dev

jobs:
  # First, run all your validation checks. This job is identical to your linting job.
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'poetry'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Run Flake8
        run: poetry run flake8 src/

      - name: Run Pylint and Check Score
        run: |
          SCORE=$(poetry run pylint src/ | tee pylint.log | tail -n 2 | grep 'Your code has been rated at' | awk '{print $7}' | cut -d'/' -f1)
          echo "Pylint score: $SCORE"
          if (( $(echo "$SCORE < 9.0" | bc -l) )); then
            echo "Pylint score is below the 9.0 threshold. Failing the build."
            exit 1
          fi

  # This job will only run if the 'validate' job succeeds
  create-pull-request:
    # Requires the 'validate' job to complete successfully
    needs: validate
    runs-on: ubuntu-latest
    
    steps:
      - name: Create Pull Request from dev to main
        uses: peter-evans/create-pull-request@v6
        with:
          # The token is required to authorize the action to create a PR.
          # GITHUB_TOKEN is automatically provided by GitHub.
          token: ${{ secrets.GITHUB_TOKEN }}
          
          # Details for the Pull Request
          commit-message: "chore: Promote dev to main"
          title: "🚀 Release Candidate: Promote dev to main"
          body: |
            This is an auto-generated PR to promote changes from the `dev` branch to `main`.
            
            - **Source Branch:** `dev`
            - **Target Branch:** `main`
            
            Please review the changes and merge if all checks pass and the release is approved.
            
            *Triggered by commit: `${{ github.sha }}`*
            
          # The branch to which you want to merge the changes
          branch: main
          
          # The base branch from which you are creating the PR
          base: dev